[workspace]
resolver = "2"
default-members = [
    "bins/led_roulette",
    "crates/stm32f3_discovery",
]
members = [
    "bins/*",
    "crates/*"
]

[profile.release]
codegen-units = 1
debug = true
lto = true
