# default runner starts a GDB session, which requires OpenOCD to be
# running, e.g.,
## openocd -f interface/stlink.cfg -f target/stm32f3x.cfg

[target.thumbv7em-none-eabi]
# uncomment this to make `cargo run` execute programs on QEMU
# runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"

# depending on your local GDB, pick one of the following
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "gdb-multiarch -q -x openocd.gdb"
runner = "probe-rs run --chip STM32F303VCTx --connect-under-reset"

rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
#   "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4 and Cortex-M7 (no FPU)

[env]
DEFMT_LOG = "trace"
